"""Add image_url to Portfolio

Revision ID: 8b3505bb24c2
Revises: ea2b5141e5ed
Create Date: 2025-05-05 16:18:21.573744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3505bb24c2'
down_revision = 'ea2b5141e5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
