"""Add portfolio table

Revision ID: b8c256b13f9b
Revises: e0abf8d0645e
Create Date: 2025-05-04 20:28:41.510161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c256b13f9b'
down_revision = 'e0abf8d0645e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypto_name', sa.String(length=100), nullable=False),
    sa.Column('amount_owned', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###
