"""Add image_url to Favorite

Revision ID: ea2b5141e5ed
Revises: b8c256b13f9b
Create Date: 2025-05-05 16:12:54.122613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2b5141e5ed'
down_revision = 'b8c256b13f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
